services:
  frontend:
    #image: rubife
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "127.0.0.1:8080:3000"
    # network_mode: "host"
    develop:
      watch: 
        # sync static content
        - path: ./frontend
          action: sync
          target: /app
          ignore:
            - node_modules/

  backend:
    #image: example/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "127.0.0.1:3000:3000"
    # network_mode: "host"
    volumes:
      # Map the backend source code to the container
      - ./backend:/app
      # Map the tempDatabase directory to persist data
      - ./backend/tempDatabase:/tempDatabase
    develop:
      watch: 
        # rebuild image and recreate service
        - path: ./backend
          ignore:
            - venv/
          action: rebuild
